import { Project } from "@/types/projects";

export const projects: Project[] = [
  {
    title: "Splyt (Awwwards Recreation)",
    description:
      "A creative website recreation inspired by Splyt on Awwwards. Developed with React, GSAP, and Tailwind CSS, showcasing fluid motion design and interactive storytelling..",
    image: "/images/dans-attempt-spylt.webp",
    categories: ["ui", "frontend"],
    tools: ["Figma", "React JS", "Tailwind CSS", "GSAP"],
    githubUrl: "https://github.com/Vader1970/dans-gsap-awwwards",
    liveUrl: "https://dans-gsap-awwwards.vercel.app",
    type: "personal",
  },
  {
    title: "Velvet Pour (Awwwards Recreation)",
    description:
      "An immersive cocktail website recreation inspired by Velvet Pour on Awwwards. Built with React, GSAP, and Tailwind CSS, featuring smooth scroll animations and cinematic interactions.",
    image: "/images/velvet-pour.webp",
    categories: ["ui", "frontend"],
    tools: ["Figma", "React JS", "Tailwind CSS", "GSAP"],
    githubUrl: "https://github.com/Vader1970/gsap_cocktails",
    liveUrl: "https://dans-gsap-cocktails.vercel.app",
    type: "personal",
  },
  {
    title: "Star Wars Memorabilia",
    description:
      "Built to catalogue my own 3,000-piece Star Wars collection, from vintage to modern memorabilia. Still in progress, but once complete it will let any collector customise categories, track valuations via eBay, and manage treasures with a built-in CMS. (Full access available on request.)",
    image: "/images/star-wars-memorabilia.webp",
    categories: ["ui", "frontend", "backend"],
    tools: ["React JS", "Next JS", "Cloudflare", "Supabase", "Tailwind CSS", "TypeScript", "API's"],
    githubUrl: "https://github.com/Vader1970/star-wars-collectors",
    liveUrl: "https://star-wars-collectors.vercel.app/",
    type: "personal",
  },
  {
    title: "AI Resume Analyzer",
    description:
      "AI-powered Resume Analyzer with React, React Router, and Puter.js! Create job listings, upload candidate resumes, and use AI to automatically evaluate and match resumes to job requirements.",
    image: "/images/resume-ai.webp",
    categories: ["ui", "frontend", "backend"],
    tools: ["Figma", "React JS", "React Router", "Puter.js", "Tailwind CSS", "JavaScript", "API's", "AI Agents"],
    githubUrl: "https://github.com/Vader1970/ai-resume-analyzer",
    liveUrl: "https://your-ai-resume-analyzer.vercel.app/",
    type: "personal",
  },
  {
    title: "Apple iPhone 15 Clone",
    description:
      "A detailed recreation of the Apple iPhone 15 Pro website, combining GSAP animations with Three.js 3D effects for a dynamic user experience.",
    image: "/images/iphone.webp",
    categories: ["ui", "frontend", "backend"],
    tools: ["Figma", "Photoshop", "React JS", "Three JS", "GSAP", "Tailwind CSS", "JavaScript", "Netlify"],
    githubUrl: "https://github.com/Vader1970/dans-iphone-15pro-clone",
    liveUrl: "https://dans-iphone-pro15-clone.netlify.app/",
    type: "personal",
  },
  {
    title: "Zentry Award Winnning Website Clone",
    description: "My clone of the award-winning Zentry website, which earned Awwwards Site of the Month recognition.",
    image: "/images/award-winning-website.webp",
    categories: ["ui", "frontend", "backend"],
    tools: ["Figma", "Photoshop", "React JS", "Tailwind CSS", "GSAP", "JavaScript", "Vercel"],
    githubUrl: "https://github.com/Vader1970/award-winning-website/tree/main",
    liveUrl: "https://award-winning-website-dans.vercel.app/",
    type: "personal",
  },
  // {
  //   title: "Brainwave",
  //   description:
  //     "A modern landing page featuring sleek parallax effects and a clean bento box layout designed to engage visitors visually.",
  //   image: "/images/brainwave.webp",
  //   categories: ["ui", "frontend"],
  //   tools: ["Figma", "Photoshop", "React JS", "GSAP", "Tailwind CSS", "JavaScript", "Vercel"],
  //   githubUrl: "https://github.com/Vader1970/dans-brainwaze/tree/main",
  //   liveUrl: "https://dans-brainwaze.vercel.app/",
  //   type: "personal",
  // },
  {
    title: "CVI Projects Limited",
    description:
      "Built a responsive landing page for CVI Projects Limited to attract trade professionals, highlighting their role in managing major residential and commercial developments.",
    image: "/images/cvi-projects.webp",
    categories: ["ui", "frontend"],
    tools: [
      "Figma",
      "UX/UI Design",
      "Photoshop",
      "Next JS",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "SEO",
      "Supabase",
      "Resend",
      "Shadcn UI",
      "Vercel",
      "Monday CRM"
    ],
    liveUrl: "https://www.cviprojects.com/",
    type: "client",
  },
  // {
  //   title: "Next JS and React JS Component Library",
  //   description:
  //     "A comprehensive library of 1,307 copy-and-paste React and Next.js components, paired with matching Figma assets for rapid app development.",
  //   image: "/images/components-library.webp",
  //   categories: ["frontend", "backend"],
  //   tools: ["UX/UI Design", "Figma", "Next JS", "React JS", "Tailwind CSS", "TypeScript", "Framer Motion", "Vercel"],
  //   // githubUrl: "https://github.com/Vader1970/components-library/tree/main",
  //   liveUrl: "https://nextjs-components-library.vercel.app/",
  //   type: "client",
  // },
  {
    title: "Chance Voight Investment Corporation",
    description: "UI/UX Designer and Web Developer for Chance Voight Investment Corporation.",
    image: "/images/chance-voight.webp",
    categories: ["ui"],
    tools: [
      "Figma",
      "UX/UI Design",
      "Photoshop",
      "Next JS",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Analytics",
      "Node JS",
      "API's",
      "Supabase",
      "Resend",
      "Vercel",
      "Monday CRM"
    ],
    liveUrl: "https://www.chancevoight.com/",
    type: "client",
  },
  {
    title: "Patterson Wealth Partners",
    description: "A clean, professional website built to reflect Patterson Wealth Partners' long-standing expertise in financial planning, wealth & tax estate management. Soon will be launched on the live domain.",
    image: "/images/patterson-wealth-partners.webp",
    categories: ["ui", "frontend", "backend"],
    tools: [
      "Figma",
      "UX/UI Design",
      "Photoshop",
      "Next JS",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "API's",
      "Pipedrive CRM",
      "Vercel",
    ],
    liveUrl: "https://patterson-wealth-partners.vercel.app/",
    type: "client",
  },
  // {
  //   title: "Burst Digital",
  //   description:
  //     "Built Burst Digital's Webflow site from start to finish, handling research, UX/UI design, client communication, and final deployment.",
  //   image: "/images/burst-digital.webp",
  //   categories: ["ui", "frontend"],
  //   tools: ["Figma", "Webflow", "UX/UI Design", "Content Management System"],
  //   liveUrl: "https://www.burstdigital.co.nz/",
  //   type: "client",
  // },
];
