import { Project } from "@/types/projects";

export const projects: Project[] = [
  {
    title: "CVI Projects Limited",
    description:
      "Built a responsive landing page for CVI Projects Limited to attract trade professionals, highlighting their role in managing major residential and commercial developments.",
    image: "/images/cvi-projects.webp",
    categories: ["ui", "frontend"],
    tools: [
      "Figma",
      "UX/UI Design",
      "Photoshop",
      "Next JS",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "SEO",
      "Supabase",
      "Resend",
      "Shadcn UI",
      "Vercel",
    ],
    liveUrl: "https://www.cviprojects.com/",
    type: "client",
  },

  {
    title: "Next JS and React JS Component Library",
    description:
      "A comprehensive library of 1,307 copy-and-paste React and Next.js components, paired with matching Figma assets for rapid app development.",
    image: "/images/components-library.webp",
    categories: ["frontend", "backend"],
    tools: ["UX/UI Design", "Figma", "Next JS", "React JS", "Tailwind CSS", "TypeScript", "Framer Motion", "Vercel"],
    // githubUrl: "https://github.com/Vader1970/components-library/tree/main",
    liveUrl: "https://nextjs-components-library.vercel.app/",
    type: "client",
  },
  {
    title: "Chance Voight Investment Corporation",
    description: "UI/UX Designer and Web Developer for Chance Voight Investment Corporation.",
    image: "/images/chance-voight.webp",
    categories: ["ui"],
    tools: [
      "Figma",
      "UX/UI Design",
      "Photoshop",
      "Next JS",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Analytics",
      "Node JS",
      "API's",
      "Supabase",
      "Resend",
      "Vercel",
    ],
    liveUrl: "https://www.chancevoight.com/",
    type: "client",
  },
  {
    title: "Brainwave",
    description:
      "A modern landing page featuring sleek parallax effects and a clean bento box layout designed to engage visitors visually.",
    image: "/images/brainwave.webp",
    categories: ["ui", "frontend"],
    tools: ["Figma", "Photoshop", "React JS", "GSAP", "Tailwind CSS", "JavaScript", "Vercel"],
    githubUrl: "https://github.com/Vader1970/dans-brainwaze/tree/main",
    liveUrl: "https://dans-brainwaze.vercel.app/",
    type: "personal",
  },
  {
    title: "Apple iPhone 15 Clone",
    description:
      "A detailed recreation of the Apple iPhone 15 Pro website, combining GSAP animations with Three.js 3D effects for a dynamic user experience.",
    image: "/images/iphone.webp",
    categories: ["ui", "frontend", "backend"],
    tools: ["Figma", "Photoshop", "React JS", "Three JS", "GSAP", "Tailwind CSS", "JavaScript", "Netlify"],
    githubUrl: "https://github.com/Vader1970/dans-iphone-15pro-clone",
    liveUrl: "https://dans-iphone-pro15-clone.netlify.app/",
    type: "personal",
  },
  {
    title: "Zentry Award Winnning Website Clone",
    description: "My clone of the award-winning Zentry website, which earned Awwwards Site of the Month recognition.",
    image: "/images/award-winning-website.webp",
    categories: ["ui", "frontend", "backend"],
    tools: ["Figma", "Photoshop", "React JS", "Tailwind CSS", "GSAP", "JavaScript", "Vercel"],
    githubUrl: "https://github.com/Vader1970/award-winning-website/tree/main",
    liveUrl: "https://award-winning-website-dans.vercel.app/",
    type: "personal",
  },
  // {
  //   title: "Burst Digital",
  //   description:
  //     "Built Burst Digital's Webflow site from start to finish, handling research, UX/UI design, client communication, and final deployment.",
  //   image: "/images/burst-digital.webp",
  //   categories: ["ui", "frontend"],
  //   tools: ["Figma", "Webflow", "UX/UI Design", "Content Management System"],
  //   liveUrl: "https://www.burstdigital.co.nz/",
  //   type: "client",
  // },
];
